# This is a basic workflow to help you get started with Actions

name: CI Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build success
        run: echo build success

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: test success
        run: echo test success

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: deploy success
        run: echo deploy success

  cleanUp:
    name: Clean up
    runs-on: ubuntu-latest

    steps:
      - name: clean up success
        run: echo clean up success